### ISSUE TITLE
Error updating field without making a change

### ISSUE THREAD

**Issue by brightbytes** [mspanc/just-datetime-picker#10] opened 2013-07-30 20:13 UTC
I get the following error in my console upon updating a datetime field to have the same value it had when the ActiveAdmin update form rendered:

Just error while trying to set scheduled_at attribute: "07/31/2013 10:00:00" is not valid date/time

I was able to create my object just fine with this datetime.

The problem appears to be that the picker displays the currently set date as "07/31/2013".  But, if I manually re-select the same date using the Date Picker, it appears as "2013-07-31", which I am then able to save.

Seems like the widget should be able to handle processing a date in the exact format it displays the date to users in.  :)

**Comment by mspanc** [comment] 2015-05-14 14:52
Duplicate of #11

**Closed by mspanc** 2015-05-14 14:52 UTC
Labels: bug, duplicate
